swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger CIM
  description: A sample API that uses a CIM profile object
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
  license:
    name: MIT
host: siemens.io
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /aclinesegment:
    get:
      operationId: web.get_aclinesegment
      description: A wire or combination of wires, with consistent electrical characteristics, building a single electrical system, used to carry alternating current between points in the power system. For symmetrical, transposed three phase lines, it is sufficient to use attributes of the line segment, which describe impedances and admittances for the entire length of the segment. Additionally impedances can be computed by using length and associated per length impedances. The BaseVoltage at the two ends of ACLineSegments in a Line shall have the same BaseVoltage.nominalVoltage. However, boundary lines may have slightly different BaseVoltage.nominalVoltages and variation is allowed. Larger voltage difference in general requires use of an equivalent branch.
      produces:
        - application/json
      responses:
        '200':
          description: AC Line Segment
          schema:
            type: array
            items:
              $ref: https://raw.githubusercontent.com/believeohiozua/talesarena/main/document.json#/definitions/ACLineSegment
