# Generated by Django 2.2 on 2019-07-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full names', max_length=200)),
                ('phone_number', models.CharField(help_text='phone number', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Project_writing_(thesis)', 'Research/project work (thesis)'), ('Data_Analysis', 'Data Analysis'), ('Content_Management', 'Content Management'), ('Web_Development', 'Web Development')], default='Project_writing_(thesis)', help_text='Service required', max_length=100)),
                ('description', models.TextField(blank=True, help_text='A brief description of the service requested', null=True)),
            ],
        ),
    ]
