# Generated by Django 2.2.4 on 2019-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.CharField(choices=[('Project_writing_(thesis)', 'Research/project work (thesis)'), ('Data_Analysis', 'Data Analysis'), ('Content_Management', 'Content Management'), ('Web_Development', 'Web Development'), ('Others', 'Others')], default='Project_writing_(thesis)', help_text='Service required', max_length=100),
        ),
    ]
